### ISSUE TITLE
会員登録 削除されたユーザとログインIDが重複すると登録できなくなっている

### ISSUE THREAD

**Issue by thonma** [skj-kensyu-2018/tamalunch#14]
アプリの入力チェックなどで、
重複するログインIDは登録できないようになっているのであれば、
以下のようにすればできそうです。

・テーブルのNOT NULL制約を外す
・ユーザ削除時、ログインIDをNULLにする
※ユニーク制約があるカラムでも、NULLは重複したことにならないため。

**Comment by takachanchan** [comment]
対応済
